export const rabbitThoughts: Record<string, { idle: string[], trip: string[], baby: string[], snake: string[] }> = {
  'en': {
    idle: [
      'Boing!',
      'Is that a carrot?',
      'Hop hop hop~',
      'Nice weather!',
      '*munch munch*',
      'So bouncy!',
      'Where am I going?',
      'Life is good~',
      'I am speed.',
      'Do I look cute?',
      'Carrots > lettuce',
      'Boing boing!',
      '*sniff sniff*',
      'Am I a bunny or a rabbit?',
      'Jump!',
      'The grass is soft~',
      'I believe I can fly!',
      'So fluffy~',
      'Another perfect hop!',
      'Who needs wings?',
      'Wheee!',
      'I smell mushrooms...',
      'Tail wiggle~',
      '♪ hop de hop ♪',
      'Watch this jump!',
      'Nap time soon...',
      'I love hopping!',
      'What a view~',
      'Dandelion!',
      'Ears up!',
      'Zoom zoom!',
      'Almost tripped!',
    ],
    trip: [
      'The colors, man...',
      'I can see sounds!',
      'Is the sky breathing?',
      'Whoooa...',
      'Everything is sparkly~',
      'Am I a cloud?',
      'The ground is waving!',
      'So many colors...',
      'I feel floaty~',
      'Wait... what?',
      'Cosmic carrots!',
      'I am the universe!',
    ],
    baby: [
      'Mama?',
      'smol boing',
      'First hop!',
      'The world is big!',
      '*tiny squeak*',
      'Hewwo!',
      'I did it!',
      'So tall up here!',
      'Where mama go?',
      'Tiny hop!',
    ],
    snake: [
      '...did that move?',
      'Ssss...?',
      'Grass is wiggly...',
    ],
  },
  'zh-CN': {
    idle: [
      '蹦!',
      '那是胡萝卜吗？',
      '蹦蹦跳跳~',
      '天气真好！',
      '*嚼嚼嚼*',
      '好弹!',
      '我要去哪呀？',
      '生活真美好~',
      '我好快！',
      '我可爱吗？',
      '胡萝卜最棒！',
      '蹦蹦!',
      '*闻闻闻*',
      '跳！',
      '草地好软~',
      '我觉得我能飞！',
      '好蓬松~',
      '完美一跳！',
      '谁需要翅膀？',
      '呜呼~',
      '闻到蘑菇了...',
      '尾巴摇摇~',
      '♪ 蹦哒蹦哒 ♪',
      '看我这一跳！',
      '快到午睡时间了...',
      '我爱蹦蹦跳！',
      '风景真好~',
      '蒲公英！',
      '耳朵竖起来！',
      '嗖嗖嗖！',
      '差点摔倒！',
      '哼哼~',
    ],
    trip: [
      '这些颜色...',
      '我能看到声音！',
      '天空在呼吸吗？',
      '哇哦...',
      '一切都在闪闪发光~',
      '我是云朵吗？',
      '地面在摇晃！',
      '好多颜色...',
      '感觉飘飘的~',
      '等等...什么？',
      '宇宙胡萝卜！',
      '我就是宇宙！',
    ],
    baby: [
      '妈妈？',
      '小小蹦',
      '第一次跳！',
      '世界好大！',
      '*小小叫*',
      '你好呀！',
      '我做到了！',
      '这里好高！',
      '妈妈去哪了？',
      '小小跳！',
    ],
    snake: [
      '...刚才动了？',
      '嘶...？',
      '草在扭...',
    ],
  },
  'zh-TW': {
    idle: [
      '蹦！',
      '那是胡蘿蔔嗎？',
      '蹦蹦跳跳~',
      '天氣真好！',
      '*嚼嚼嚼*',
      '好彈！',
      '我要去哪呀？',
      '生活真美好~',
      '我好快！',
      '我可愛嗎？',
      '胡蘿蔔最棒！',
      '蹦蹦！',
      '*聞聞聞*',
      '跳！',
      '草地好軟~',
      '我覺得我能飛！',
      '好蓬鬆~',
      '完美一跳！',
      '誰需要翅膀？',
      '嗚呼~',
      '聞到蘑菇了...',
      '尾巴搖搖~',
      '♪ 蹦噠蹦噠 ♪',
      '看我這一跳！',
      '快到午睡時間了...',
      '我愛蹦蹦跳！',
      '風景真好~',
      '蒲公英！',
      '耳朵豎起來！',
      '咻咻咻！',
      '差點摔倒！',
      '哼哼~',
    ],
    trip: [
      '這些顏色...',
      '我能看到聲音！',
      '天空在呼吸嗎？',
      '哇喔...',
      '一切都在閃閃發光~',
      '我是雲朵嗎？',
      '地面在搖晃！',
      '好多顏色...',
      '感覺飄飄的~',
      '等等...什麼？',
      '宇宙胡蘿蔔！',
      '我就是宇宙！',
    ],
    baby: [
      '媽媽？',
      '小小蹦',
      '第一次跳！',
      '世界好大！',
      '*小小叫*',
      '你好呀！',
      '我做到了！',
      '這裡好高！',
      '媽媽去哪了？',
      '小小跳！',
    ],
    snake: [
      '...剛才動了？',
      '嘶...？',
      '草在扭...',
    ],
  },
  'ja': {
    idle: [
      'ぴょん！',
      'にんじんかな？',
      'ぴょんぴょん~',
      'いい天気！',
      '*もぐもぐ*',
      'よく弾む！',
      'どこ行くの？',
      '幸せ~',
      '速い！',
      'かわいい？',
      'にんじん最高！',
      'ぴょんぴょん！',
      '*くんくん*',
      'ジャンプ！',
      '草がふわふわ~',
      '飛べる気がする！',
      'もふもふ~',
      '完璧なジャンプ！',
      '翼なんていらない！',
      'わーい！',
      'きのこの匂い...',
      'しっぽフリフリ~',
      '♪ ぴょんぴょん ♪',
      '見てて！',
      'もうすぐお昼寝...',
      'ジャンプ大好き！',
      'いい景色~',
      'たんぽぽ！',
      'お耳ピーン！',
      'びゅーん！',
      'あぶなかった！',
      'ふんふん~',
    ],
    trip: [
      'この色は...',
      '音が見える！',
      '空が呼吸してる？',
      'うわぁ...',
      'キラキラ~',
      '雲になった？',
      '地面がゆらゆら！',
      '色がいっぱい...',
      'ふわふわする~',
      'え...なに？',
      '宇宙のにんじん！',
      '私が宇宙！',
    ],
    baby: [
      'ママ？',
      'ちいさくぴょん',
      'はじめてのジャンプ！',
      '世界おっきい！',
      '*きゅっ*',
      'こんにちは！',
      'できた！',
      'たかーい！',
      'ママどこ？',
      'ちいさくジャンプ！',
    ],
    snake: [
      '...今動いた？',
      'シュル...？',
      '草がもぞもぞ...',
    ],
  },
  'ko': {
    idle: [
      '깡충!',
      '당근이다?',
      '깡충깡충~',
      '날씨 좋다!',
      '*냠냠냠*',
      '통통!',
      '어디 가는 거지?',
      '행복해~',
      '나 빠르다!',
      '나 귀여워?',
      '당근 최고!',
      '깡충깡충!',
      '*킁킁*',
      '점프!',
      '잔디가 부드러워~',
      '날 수 있을 것 같아!',
      '포근포근~',
      '완벽한 점프!',
      '날개 필요 없어!',
      '우와~',
      '버섯 냄새...',
      '꼬리 흔들흔들~',
      '♪ 통통통 ♪',
      '이것 봐!',
      '곧 낮잠 시간...',
      '점프 좋아!',
      '경치 좋다~',
      '민들레!',
      '귀 쫑긋!',
      '슝슝!',
      '앗 미끄러질 뻔!',
      '흥흥~',
    ],
    trip: [
      '이 색깔들...',
      '소리가 보여!',
      '하늘이 숨 쉬어?',
      '우와...',
      '반짝반짝~',
      '나 구름이야?',
      '바닥이 흔들려!',
      '색이 너무 많아...',
      '둥둥 떠다니는 기분~',
      '잠깐... 뭐?',
      '우주 당근!',
      '내가 우주야!',
    ],
    baby: [
      '엄마?',
      '작은 깡충',
      '첫 점프!',
      '세상이 크다!',
      '*삐약*',
      '안녕!',
      '해냈다!',
      '여기 높다!',
      '엄마 어디?',
      '작은 점프!',
    ],
    snake: [
      '...지금 움직였어?',
      '스스...?',
      '풀이 꿈틀...',
    ],
  },
  'ru': {
    idle: [
      'Прыг!',
      'Это морковка?',
      'Прыг-скок~',
      'Хорошая погода!',
      '*хрум-хрум*',
      'Как пружинка!',
      'Куда я иду?',
      'Жизнь прекрасна~',
      'Я быстрый!',
      'Я милый?',
      'Морковка — лучше всех!',
      'Прыг-прыг!',
      '*нюх-нюх*',
      'Прыжок!',
      'Трава мягкая~',
      'Я верю, что могу летать!',
      'Такой пушистый~',
      'Идеальный прыжок!',
      'Кому нужны крылья?',
      'Уии~',
      'Пахнет грибами...',
      'Хвостик виляет~',
      '♪ прыг да скок ♪',
      'Смотри, как прыгаю!',
      'Скоро сон...',
      'Обожаю прыгать!',
      'Какой вид~',
      'Одуванчик!',
      'Ушки торчком!',
      'Вжух!',
      'Чуть не упал!',
      'Хм-хм~',
    ],
    trip: [
      'Эти цвета...',
      'Я вижу звуки!',
      'Небо дышит?',
      'Ого...',
      'Всё сверкает~',
      'Я облако?',
      'Земля качается!',
      'Столько цветов...',
      'Я парю~',
      'Подожди... что?',
      'Космическая морковка!',
      'Я — вселенная!',
    ],
    baby: [
      'Мама?',
      'Маленький прыг',
      'Первый прыжок!',
      'Мир такой большой!',
      '*пиу-пиу*',
      'Пивет!',
      'Получилось!',
      'Тут высоко!',
      'Где мама?',
      'Прыг-малыш!',
    ],
    snake: [
      '...шевелится?',
      'Ссс...?',
      'Трава дрожит...',
    ],
  },
  'es': {
    idle: [
      '¡Boing!',
      '¿Eso es una zanahoria?',
      'Hop hop hop~',
      '¡Buen tiempo!',
      '*ñam ñam*',
      '¡Qué rebote!',
      '¿A dónde voy?',
      'La vida es bella~',
      '¡Soy veloz!',
      '¿Soy lindo?',
      '¡Zanahorias > lechuga!',
      '¡Boing boing!',
      '*snif snif*',
      '¡Salto!',
      'El pasto es suave~',
      '¡Creo que puedo volar!',
      'Qué esponjoso~',
      '¡Salto perfecto!',
      '¿Quién necesita alas?',
      '¡Yupi~!',
      'Huelo hongos...',
      'Colita wiggle~',
      '♪ hop hop ♪',
      '¡Mira este salto!',
      'Hora de siesta pronto...',
      '¡Me encanta saltar!',
      'Qué vista~',
      '¡Diente de león!',
      '¡Orejas arriba!',
      '¡Zum zum!',
      '¡Casi me caigo!',
      'Hmm hmm~',
    ],
    trip: [
      'Los colores...',
      '¡Puedo ver sonidos!',
      '¿El cielo respira?',
      'Guau...',
      'Todo brilla~',
      '¿Soy una nube?',
      '¡El suelo se mueve!',
      'Tantos colores...',
      'Me siento flotando~',
      'Espera... ¿qué?',
      '¡Zanahorias cósmicas!',
      '¡Soy el universo!',
    ],
    baby: [
      '¿Mamá?',
      'boing chiquito',
      '¡Primer salto!',
      '¡El mundo es grande!',
      '*squeak pequeño*',
      '¡Holi!',
      '¡Lo logré!',
      '¡Qué alto!',
      '¿Dónde está mamá?',
      '¡Saltito!',
    ],
    snake: [
      '...se movió?',
      'Ssss...?',
      'El pasto tiembla...',
    ],
  },
  'fr': {
    idle: [
      'Boing !',
      'C\'est une carotte ?',
      'Hop hop hop~',
      'Beau temps !',
      '*miam miam*',
      'Ça rebondit !',
      'Où je vais ?',
      'La vie est belle~',
      'Je suis rapide !',
      'Je suis mignon ?',
      'Carottes > laitue !',
      'Boing boing !',
      '*snif snif*',
      'Saute !',
      'L\'herbe est douce~',
      'Je crois que je peux voler !',
      'Tout doux~',
      'Saut parfait !',
      'Pas besoin d\'ailes !',
      'Youpi~',
      'Ça sent les champignons...',
      'Queue qui frétille~',
      '♪ hop la hop ♪',
      'Regarde ce saut !',
      'Bientôt la sieste...',
      'J\'adore sauter !',
      'Quelle vue~',
      'Pissenlit !',
      'Oreilles dressées !',
      'Zoum zoum !',
      'J\'ai failli tomber !',
      'Hmm hmm~',
    ],
    trip: [
      'Ces couleurs...',
      'Je vois des sons !',
      'Le ciel respire ?',
      'Waouh...',
      'Tout scintille~',
      'Je suis un nuage ?',
      'Le sol ondule !',
      'Tant de couleurs...',
      'Je flotte~',
      'Attends... quoi ?',
      'Carottes cosmiques !',
      'Je suis l\'univers !',
    ],
    baby: [
      'Maman ?',
      'petit boing',
      'Premier saut !',
      'Le monde est grand !',
      '*petit couic*',
      'Coucou !',
      'J\'ai réussi !',
      'C\'est haut ici !',
      'Où est maman ?',
      'Petit saut !',
    ],
    snake: [
      '...ça a bougé ?',
      'Ssss...?',
      'L\'herbe frémit...',
    ],
  },
  'ar': {
    idle: [
      'قفز!',
      'هل تلك جزرة؟',
      'نط نط نط~',
      'طقس جميل!',
      '*مقرمش*',
      'يا للقفز!',
      'إلى أين أذهب؟',
      'الحياة حلوة~',
      'أنا سريع!',
      'هل أنا لطيف؟',
      'الجزر أفضل!',
      'قفز قفز!',
      '*شم شم*',
      'اقفز!',
      'العشب ناعم~',
      'أظن أني أستطيع الطيران!',
      'ناعم جداً~',
      'قفزة مثالية!',
      'من يحتاج أجنحة؟',
      'ياي~',
      'أشم فطر...',
      'ذيلي يهتز~',
      '♪ نط نط ♪',
      'انظر لقفزتي!',
      'وقت القيلولة قريب...',
      'أحب القفز!',
      'يا لها من إطلالة~',
      'هندباء!',
      'آذان للأعلى!',
      'زووم!',
      'كدت أسقط!',
      'هم هم~',
    ],
    trip: [
      'هذه الألوان...',
      'أستطيع رؤية الأصوات!',
      'هل السماء تتنفس؟',
      'واو...',
      'كل شيء يلمع~',
      'هل أنا غيمة؟',
      'الأرض تتمايل!',
      'كم من الألوان...',
      'أشعر بأنني أطفو~',
      'انتظر... ماذا؟',
      'جزر كونية!',
      'أنا الكون!',
    ],
    baby: [
      'ماما؟',
      'قفزة صغيرة',
      'أول قفزة!',
      'العالم كبير!',
      '*صرير صغير*',
      'مرحباً!',
      'فعلتها!',
      'عالٍ هنا!',
      'أين ماما؟',
      'نطة صغيرة!',
    ],
    snake: [
      '...تحرّك؟',
      'سسس...؟',
      'العشب يرتجف...',
    ],
  },
}

export const snakeHisses: Record<string, string[]> = {
  'en': [
    'Hssss!',
    'Go away!',
    'Don\'t touch!',
    '*rattle rattle*',
    'I was napping!',
  ],
  'zh-CN': [
    '嘶嘶嘶！',
    '走开！',
    '别碰我！',
    '*沙沙沙*',
    '我在睡觉！',
  ],
  'zh-TW': [
    '嘶嘶嘶！',
    '走開！',
    '別碰我！',
    '*沙沙沙*',
    '我在睡覺！',
  ],
  'ja': [
    'シャー！',
    'あっち行って！',
    '触らないで！',
    '*カラカラ*',
    '寝てたのに！',
  ],
  'ko': [
    '쉬이익!',
    '저리 가!',
    '만지지 마!',
    '*딸랑딸랑*',
    '자고 있었는데!',
  ],
  'ru': [
    'Шшш!',
    'Уходи!',
    'Не трогай!',
    '*трещ-трещ*',
    'Я спал!',
  ],
  'es': [
    '¡Ssss!',
    '¡Fuera!',
    '¡No toques!',
    '*cascabel*',
    '¡Estaba durmiendo!',
  ],
  'fr': [
    'Sssss !',
    'Va-t\'en !',
    'Touche pas !',
    '*crotale*',
    'Je dormais !',
  ],
  'ar': [
    'هسسس!',
    'ابتعد!',
    'لا تلمسني!',
    '*خشخشة*',
    'كنت نائماً!',
  ],
}
